### PR TITLE
Use hyper instead of Tokio Curl

### PR DESCRIPTION
**Pull request by asonix**
I've rebased my Hyper changes on top of your Failure changes. I'll continue to keep this branch up-to-date until it's ready to be merged.

### CODE REVIEW

**Comment by bytesnake** [comment]
Ok, I hope this will happen in the near future. I have unfortunately not enough time to implement a server multipart library, but perhaps multipart-async will be stable enough in the future. BTW: have you an idea how I can get rid of the ErrorKing to Error conversions? I implemented it, but the manual conversion with Error::from is a bit tedious.

**Comment by asonix** [comment]
I published my fork of the multipart library. It still doesn't have server-side support, but now it's on crates.io so you can actually publish things that depend on it.

**Comment by asonix** [comment]
The author of the original hyper multipart library finally responded! Maybe we'll get the changes from my fork upstreamed.

**Comment by asonix** [comment]
Upstream accepted my changes, so now I'm not maintaining a fork of the multipart library

**Pull request merged**
